---
title: "Dashboard Template"
author: "Jemma Marcus-Shi and Linjie Zhu"
date: "`r Sys.Date()`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
---

# Questions and Written Insights

Question 1: where students are by region/state

Question 2: city rank by job opportunities













```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)

#package intialization
if(require(pacman)==FALSE) install.packages("pacman")
pacman::p_load(tidyverse, #for data manipulation
               plotly, #for interactive plots
               flexdashboard, #to make a dashboard
               fontawesome, #for icons
               DT #for better tables
               )

#read in data
internraw=readRDS("final_intern_data2021.rds")
```

# Survey Overview {data-orientation="columns"}

Overview of survey responses

## row {data-width="300"}

### Response Rate

```{r, echo = FALSE}
rate = round(100*nrow(internraw)/800,0)
gauge(rate, min=0, max = 100, symbol = '%', gaugeSectors(success = c(80,100), warning=c(40,79), danger = c(0, 39)))
```